# Generated by Django 4.2.2 on 2023-06-21 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=200, verbose_name='User Name')),
                ('user_lname', models.CharField(max_length=200, verbose_name='Last Name')),
                ('user_email', models.CharField(max_length=200, unique=True, verbose_name='Email')),
                ('user_position', models.CharField(max_length=200, verbose_name='Position')),
                ('pub_date', models.DateField(default=datetime.datetime(2023, 6, 21, 9, 6, 48, 595699, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
