# Generated by Django 4.2.2 on 2023-06-22 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_id_alter_user_pub_date_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 6, 2, 2, 478105, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 22, 6, 2, 2, 478105, tzinfo=datetime.timezone.utc)),
        ),
    ]
